### ISSUE TITLE
Last step issue!!

### ISSUE THREAD

**Issue by ewan2411ethan** [NVlabs/FoundationPose#230]
when i run this step # Build extensions
export CMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH:/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/pybind11/share/cmake/pybind11"
bash build_all_conda.sh

it shows like:
[100%] Linking CXX shared module mycpp.cpython-39-x86_64-linux-gnu.so
[100%] Built target mycpp
Obtaining file:///home/dlweg/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  DEPRECATION: Legacy editable install of common==0.0.0 from file:///home/dlweg/FoundationPose/bundlesdf/mycuda (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for common
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [113 lines of output]
        /home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        running develop
        /home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************

        !!
          easy_install.initialize_options(self)
        /home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************

        !!
 self.initialize_options()
    running egg_info
    creating common.egg-info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    writing manifest file 'common.egg-info/SOURCES.txt'
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    /home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
      warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
    building 'common' extension
    creating /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
    Emitting ninja build file /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] /home/dlweg/FoundationPose/cuda-11.8/bin/nvcc  -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/home/dlweg/FoundationPose/cuda-11.8/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/dlweg/miniconda3/envs/foundationpose/include/python3.9 -I/home/dlweg/miniconda3/envs/foundationpose/include/python3.9 -c -c /home/dlweg/FoundationPose/bundlesdf/mycuda/common.cu -o /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
    FAILED: /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
    /home/dlweg/FoundationPose/cuda-11.8/bin/nvcc  -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/home/dlweg/FoundationPose/cuda-11.8/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/dlweg/miniconda3/envs/foundationpose/include/python3.9 -I/home/dlweg/miniconda3/envs/foundationpose/include/python3.9 -c -c /home/dlweg/FoundationPose/bundlesdf/mycuda/common.cu -o /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
    /home/dlweg/FoundationPose/bundlesdf/mycuda/common.cu:26:10: fatal error: Eigen/Dense: No such file or directory
       26 | #include "Eigen/Dense"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    [2/2] c++ -MMD -MF /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /home/dlweg/miniconda3/envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/dlweg/miniconda3/envs/foundationpose/include -fPIC -O2 -isystem /home/dlweg/miniconda3/envs/foundationpose/include -fPIC -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/home/dlweg/FoundationPose/cuda-11.8/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/dlweg/miniconda3/envs/foundationpose/include/python3.9 -I/home/dlweg/miniconda3/envs/foundationpose/include/python3.9 -c -c /home/dlweg/FoundationPose/bundlesdf/mycuda/bindings.cpp -o /home/dlweg/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
        subprocess.run(
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/dlweg/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
        setup(
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
        return run_commands(dist)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
        dist.run_commands()
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
        self.run_command(cmd)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
        super().run_command(command)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 35, in run
        self.install_for_development()
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 112, in install_for_development
        self.run_command('build_ext')
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
        super().run_command(command)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 98, in run
        _build_ext.run(self)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
        self._build_extensions_serial()
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
        objects = self.compiler.compile(
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/dlweg/miniconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by zhaowangji** [comment]
the same.still don't know how to fix it

**Comment by zhaowangji** [comment]
well, you should look at this issue.
I solved by pulling his image(I had not tried to use conda to see whether it would work):https://github.com/NVlabs/FoundationPose/issues/27
it seems that it is because CUDA 11.3 does not support new GPUs(like, mine is 4060). You may notice that there is a report:Unsupported gpu architecture ‘compute_89‘.
I tried some methods, only pulling his image worked.

**Comment by foamposite** [comment]
I have the similar problem as you have mentioned. For my situation, it turns out that the compiler selects wrong "Eigen3" library when compiling the code. It have selected the Eigen3 in "usr/local", which was previously built for other project, not the Eigen3 installed in the conda environment. So the "include_dirs" in "FoundationPose-main/bundlesdf/mycuda/setup.py" line 35 should be modified as "path/to/your/eigen3/in/anaconda".
