### ISSUE TITLE
Problems with running the model-based demo

### ISSUE THREAD

**Issue by mike55688** [NVlabs/FoundationPose#236]
Hello I am running the model based demo according to the github tutorials 「python run_demo.py,」 but it comes up with the following problem, how can I fix the problem I am currently experiencing?

＝＝＝＝＝＝＝＝＝problems＝＝＝＝＝＝＝＝＝(foundationpose) kai@2080ti:~/FoundationPose$ python run_demo.py
RuntimeError: CPU dispatcher tracer already initlized
RuntimeError: CPU dispatcher tracer already initlized
RuntimeError: CPU dispatcher tracer already initlized
Traceback (most recent call last):
  File "/home/kai/FoundationPose/run_demo.py", line 10, in <module>
    from estimater import *
  File "/home/kai/FoundationPose/estimater.py", line 10, in <module>
    from Utils import *
  File "/home/kai/FoundationPose/Utils.py", line 12, in <module>
    from pytorch3d.renderer import FoVPerspectiveCameras, PerspectiveCameras, look_at_view_transform, look_at_rotation, RasterizationSettings, MeshRenderer, MeshRasterizer, BlendParams, SoftSilhouetteShader, HardPhongShader, PointLights, TexturesVertex
  File "/home/kai/anaconda3/envs/foundationpose/lib/python3.9/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/home/kai/anaconda3/envs/foundationpose/lib/python3.9/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: /home/kai/anaconda3/envs/foundationpose/lib/python3.9/site-packages/pytorch3d/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

**Comment by wenbowen123** [comment]
this looks like pytorch3d was not setup well. Did you try docker?
