### ISSUE TITLE
Testing on Google Colab

### ISSUE THREAD

**Issue by kappa95** [NVlabs/FoundationPose#239]
Someone has tried to use FoundationPose from Google Colab?

**Comment by vicky1626** [comment]
me

**Comment by superseppl** [comment]
And did it work? Did you faced some issues?

**Comment by kappa95** [comment]
I have faced some issue in the sense that i have installed the libraries manually and google colab is updating python version. So I have installed the same python version of FoundationPose and then installed all the requirements

**Comment by blanklavender** [comment]
It throws me errors about files that dont exist in the repository. Does anyone have any clue how to deal with this?

```
/content/FoundationPose
Building bundlesdf/mycuda...
/content/FoundationPose/bundlesdf/mycuda
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 15, in <module>
NameError: name '__file__' is not defined. Did you mean: '__name__'?

Building pose_est/mycuda...
[Errno 2] No such file or directory: '/content/FoundationPose/pose_est/mycuda'
/content/FoundationPose/bundlesdf/mycuda
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 15, in <module>
NameError: name '__file__' is not defined. Did you mean: '__name__'?
/content/FoundationPose

✓ Build complete (CUDA check bypassed)
```
