### ISSUE TITLE
No module named 'gridencoder'

### ISSUE THREAD

**Issue by 39GodMissing** [NVlabs/FoundationPose#247]
After configuring the environment according to readme，I ran the following command：python bundlesdf/run_nerf.py --ref_view_dir /mnt/9a72c439-d0a7-45e8-8d20-d7a235d02763/DATASET/YCB_Video/bowen_addon/ref_views_16 --dataset ycbv
The following error occurred：

Traceback (most recent call last):
  File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 113, in <module>
    run_ycbv()
  File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 85, in run_ycbv
    mesh = run_one_ob(base_dir=base_dir, cfg=cfg)
  File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 73, in run_one_ob
    mesh = run_neural_object_field(cfg, K, rgbs, depths, masks, cam_in_obs, save_dir=save_dir, debug=0)
  File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 39, in run_neural_object_field
    nerf = NerfRunner(cfg, rgbs_, depths_, masks_, normal_maps=None, poses=poses, K=K, occ_masks=None, build_octree_pcd=pcd_normalized)
  File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 158, in __init__
    self.create_nerf()
  File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 209, in create_nerf
    embed_fn, input_ch = get_embedder(self.cfg['multires'], self.cfg, i=self.cfg['i_embed'], octree_m=self.octree_m)
  File "/root/FoundationPose-main/bundlesdf/nerf_helpers.py", line 204, in get_embedder
    from mycuda.torch_ngp_grid_encoder.grid import GridEncoder
  File "/root/FoundationPose-main/bundlesdf/mycuda/torch_ngp_grid_encoder/grid.py", line 14, in <module>
    import gridencoder
ModuleNotFoundError: No module named 'gridencoder'    

Can you tell me how to solve this problem?

**Comment by wangyan-hlab** [comment]
> After configuring the environment according to readme，I ran the following command：python bundlesdf/run_nerf.py --ref_view_dir /mnt/9a72c439-d0a7-45e8-8d20-d7a235d02763/DATASET/YCB_Video/bowen_addon/ref_views_16 --dataset ycbv The following error occurred：
> 
> Traceback (most recent call last): File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 113, in run_ycbv() File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 85, in run_ycbv mesh = run_one_ob(base_dir=base_dir, cfg=cfg) File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 73, in run_one_ob mesh = run_neural_object_field(cfg, K, rgbs, depths, masks, cam_in_obs, save_dir=save_dir, debug=0) File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 39, in run_neural_object_field nerf = NerfRunner(cfg, rgbs_, depths_, masks_, normal_maps=None, poses=poses, K=K, occ_masks=None, build_octree_pcd=pcd_normalized) File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 158, in **init** self.create_nerf() File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 209, in create_nerf embed_fn, input_ch = get_embedder(self.cfg['multires'], self.cfg, i=self.cfg['i_embed'], octree_m=self.octree_m) File "/root/FoundationPose-main/bundlesdf/nerf_helpers.py", line 204, in get_embedder from mycuda.torch_ngp_grid_encoder.grid import GridEncoder File "/root/FoundationPose-main/bundlesdf/mycuda/torch_ngp_grid_encoder/grid.py", line 14, in import gridencoder ModuleNotFoundError: No module named 'gridencoder'
> 
> Can you tell me how to solve this problem?

Hi, have you solved it? I met the same problem.

**Comment by 39GodMissing** [comment]
this means that cmake failed.&nbsp;Gridencoder is a library in C++. Please strictly follow the cmake tutorial in readme to ensure successful cmake.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WANG ***@***.***&gt;; 
发送时间: 2025年4月1日(星期二) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [NVlabs/FoundationPose] No module named &#39;gridencoder&#39; (Issue #247)












    
After configuring the environment according to readme，I ran the following command：python bundlesdf/run_nerf.py --ref_view_dir /mnt/9a72c439-d0a7-45e8-8d20-d7a235d02763/DATASET/YCB_Video/bowen_addon/ref_views_16 --dataset ycbv The following error occurred：
 
Traceback (most recent call last): File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 113, in run_ycbv() File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 85, in run_ycbv mesh = run_one_ob(base_dir=base_dir, cfg=cfg) File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 73, in run_one_ob mesh = run_neural_object_field(cfg, K, rgbs, depths, masks, cam_in_obs, save_dir=save_dir, debug=0) File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 39, in run_neural_object_field nerf = NerfRunner(cfg, rgbs_, depths_, masks_, normal_maps=None, poses=poses, K=K, occ_masks=None, build_octree_pcd=pcd_normalized) File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 158, in init self.create_nerf() File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 209, in create_nerf embed_fn, input_ch = get_embedder(self.cfg['multires'], self.cfg, i=self.cfg['i_embed'], octree_m=self.octree_m) File "/root/FoundationPose-main/bundlesdf/nerf_helpers.py", line 204, in get_embedder from mycuda.torch_ngp_grid_encoder.grid import GridEncoder File "/root/FoundationPose-main/bundlesdf/mycuda/torch_ngp_grid_encoder/grid.py", line 14, in import gridencoder ModuleNotFoundError: No module named 'gridencoder'
 
Can you tell me how to solve this problem?
  
Hi, have you solved it? I met the same problem.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
  wangyan-hlab left a comment (NVlabs/FoundationPose#247)
  
After configuring the environment according to readme，I ran the following command：python bundlesdf/run_nerf.py --ref_view_dir /mnt/9a72c439-d0a7-45e8-8d20-d7a235d02763/DATASET/YCB_Video/bowen_addon/ref_views_16 --dataset ycbv The following error occurred：
 
Traceback (most recent call last): File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 113, in run_ycbv() File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 85, in run_ycbv mesh = run_one_ob(base_dir=base_dir, cfg=cfg) File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 73, in run_one_ob mesh = run_neural_object_field(cfg, K, rgbs, depths, masks, cam_in_obs, save_dir=save_dir, debug=0) File "/root/FoundationPose-main/bundlesdf/run_nerf.py", line 39, in run_neural_object_field nerf = NerfRunner(cfg, rgbs_, depths_, masks_, normal_maps=None, poses=poses, K=K, occ_masks=None, build_octree_pcd=pcd_normalized) File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 158, in init self.create_nerf() File "/root/FoundationPose-main/bundlesdf/nerf_runner.py", line 209, in create_nerf embed_fn, input_ch = get_embedder(self.cfg['multires'], self.cfg, i=self.cfg['i_embed'], octree_m=self.octree_m) File "/root/FoundationPose-main/bundlesdf/nerf_helpers.py", line 204, in get_embedder from mycuda.torch_ngp_grid_encoder.grid import GridEncoder File "/root/FoundationPose-main/bundlesdf/mycuda/torch_ngp_grid_encoder/grid.py", line 14, in import gridencoder ModuleNotFoundError: No module named 'gridencoder'
 
Can you tell me how to solve this problem?
  
Hi, have you solved it? I met the same problem.
