### ISSUE TITLE
errors when building extensions

### ISSUE THREAD

**Issue by LittlePotatoChip** [NVlabs/FoundationPose#253]
`ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
            subprocess.run(
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`

**Comment by LittlePotatoChip** [comment]
I have tried docker version，but mirror sites is not usable recently so I failed.

**Comment by LittlePotatoChip** [comment]
I found that it was not about ninja,it was caused because of eigen3,I forgot to type the complete information:
`
(foundationpose) potato@potato-MS-7E13:~/workplace/FoundationPose$ CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:10 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: system program_options
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
CMake Warning (dev) at /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/FindPythonLibsNew.cmake:101 (message):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning, or
  preferably upgrade to using FindPython, either by calling it explicitly
  before pybind11, or by setting PYBIND11_FINDPYTHON ON before pybind11.
Call Stack (most recent call first):
  /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/pybind11Tools.cmake:50 (find_package)
  /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/pybind11Common.cmake:192 (include)
  /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/pybind11Config.cmake:250 (include)
  CMakeLists.txt:13 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /home/potato/miniforge3/envs/foundationpose/bin/python (found suitable version "3.9.20", minimum required is "3.6")
-- Found PythonLibs: /home/potato/miniforge3/envs/foundationpose/lib/libpython3.9.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/pybind11/include (found version "2.12.0")
-- Configuring done (0.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/potato/workplace/FoundationPose/mycpp/build
[ 33%] Building CXX object CMakeFiles/mycpp.dir/src/app/pybind_api.cpp.o
[ 66%] Building CXX object CMakeFiles/mycpp.dir/src/Utils.cpp.o
/home/potato/workplace/FoundationPose/mycpp/src/app/pybind_api.cpp: In function ‘vectorMatrix4f cluster_poses(float, float, const vectorMatrix4f&, const vectorMatrix4f&)’:
/home/potato/workplace/FoundationPose/mycpp/src/app/pybind_api.cpp:26:38: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
   26 |   printf("num original candidates = %d\n",poses_in.size());
      |                                     ~^    ~~~~~~~~~~~~~~~
      |                                      |                 |
      |                                      int               std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type {aka long unsigned int}
      |                                     %ld
/home/potato/workplace/FoundationPose/mycpp/src/app/pybind_api.cpp:66:42: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
   66 |   printf("num of pose after clustering: %d\n",poses_out.size());
      |                                         ~^    ~~~~~~~~~~~~~~~~
      |                                          |                  |
      |                                          int                std::vector<Eigen::Matrix<float, 4, 4>, Eigen::aligned_allocator<Eigen::Matrix<float, 4, 4> > >::size_type {aka long unsigned int}
      |                                         %ld
[100%] Linking CXX shared module mycpp.cpython-39-x86_64-linux-gnu.so
[100%] Built target mycpp
Obtaining file:///home/potato/workplace/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  DEPRECATION: Legacy editable install of common==0.0.0 from file:///home/potato/workplace/FoundationPose/bundlesdf/mycuda (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for common
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [113 lines of output]
        /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        running develop
        /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running egg_info
        creating common.egg-info
        writing common.egg-info/PKG-INFO
        writing dependency_links to common.egg-info/dependency_links.txt
        writing top-level names to common.egg-info/top_level.txt
        writing manifest file 'common.egg-info/SOURCES.txt'
        reading manifest file 'common.egg-info/SOURCES.txt'
        writing manifest file 'common.egg-info/SOURCES.txt'
        running build_ext
        /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
          warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
        building 'common' extension
        creating /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
        Emitting ninja build file /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
        Compiling objects...
        Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
        [1/2] /usr/bin/nvcc  -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -c -c /home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu -o /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
        FAILED: /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
        /usr/bin/nvcc  -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -c -c /home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu -o /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
        /home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu:26:10: fatal error: Eigen/Dense: No such file or directory
           26 | #include "Eigen/Dense"
              |          ^~~~~~~~~~~~~
        compilation terminated.
        [2/2] c++ -MMD -MF /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /home/potato/miniforge3/envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/potato/miniforge3/envs/foundationpose/include -fPIC -O2 -isystem /home/potato/miniforge3/envs/foundationpose/include -fPIC -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -c -c /home/potato/workplace/FoundationPose/bundlesdf/mycuda/bindings.cpp -o /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
            subprocess.run(
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/potato/workplace/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
            setup(
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
            return distutils.core.setup(**attrs)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
            return run_commands(dist)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
            dist.run_commands()
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
            self.run_command(cmd)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 999, in run_command
            super().run_command(command)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
            cmd_obj.run()
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 35, in run
            self.install_for_development()
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 112, in install_for_development
            self.run_command('build_ext')
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
            self.distribution.run_command(command)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 999, in run_command
            super().run_command(command)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
            cmd_obj.run()
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 98, in run
            _build_ext.run(self)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
            self.build_extensions()
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
            build_ext.build_extensions(self)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
            self._build_extensions_serial()
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
            self.build_extension(ext)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
            _build_ext.build_extension(self, ext)
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
            objects = self.compiler.compile(
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
            _write_ninja_file_and_compile_objects(
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
            _run_ninja_build(
          File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
            raise RuntimeError(message) from e
        RuntimeError: Error compiling objects for extension
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [113 lines of output]
    /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cflags'
      warnings.warn(msg)
    /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
      warnings.warn(msg)
    running develop
    /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    creating common.egg-info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    writing manifest file 'common.egg-info/SOURCES.txt'
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    /home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
      warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
    building 'common' extension
    creating /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
    Emitting ninja build file /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] /usr/bin/nvcc  -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -c -c /home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu -o /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
    FAILED: /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
    /usr/bin/nvcc  -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -c -c /home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu -o /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
    /home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu:26:10: fatal error: Eigen/Dense: No such file or directory
       26 | #include "Eigen/Dense"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    [2/2] c++ -MMD -MF /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /home/potato/miniforge3/envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/potato/miniforge3/envs/foundationpose/include -fPIC -O2 -isystem /home/potato/miniforge3/envs/foundationpose/include -fPIC -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -I/home/potato/miniforge3/envs/foundationpose/include/python3.9 -c -c /home/potato/workplace/FoundationPose/bundlesdf/mycuda/bindings.cpp -o /home/potato/workplace/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
        subprocess.run(
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/potato/workplace/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
        setup(
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
        return run_commands(dist)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
        dist.run_commands()
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
        self.run_command(cmd)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 999, in run_command
        super().run_command(command)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 35, in run
        self.install_for_development()
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 112, in install_for_development
        self.run_command('build_ext')
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 999, in run_command
        super().run_command(command)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 98, in run
        _build_ext.run(self)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
        self._build_extensions_serial()
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
        objects = self.compiler.compile(
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/potato/miniforge3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
`
The error was caused by 
‘/home/potato/workplace/FoundationPose/bundlesdf/mycuda/common.cu:26:10: fatal error: Eigen/Dense: No such file or directory’
I changed this file and add this line:
'FoundationPose/bundlesdf/mycuda/setup.py'
It worked.

Hoping to help others with similar problems

**Comment by lala-sean** [comment]
Very helpful! Thanks!

**Comment by agshar96** [comment]
This was very very helpful. Thank you so much
