### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by LiYan-pro** [NVlabs/FoundationPose#266]

**Comment by LiYan-pro** [comment]
Does this rpo only support setup environmrnt on Docker or Linux?
When I want to setup enviroment on Windows, I can never success, seems like **pin==2.7.0 can't be install on Windows** ,the main error like this:
```
Obtaining file:///D:/code/other/pin-2.7.0
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [239 lines of output]
      Collecting cmeel-boost~=1.83.0
        Using cached cmeel_boost-1.83.0.tar.gz (4.0 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [178 lines of output]
        -- Building for: Visual Studio 16 2019
        -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
        -- The C compiler identification is MSVC 19.29.30153.0
        -- The CXX compiler identification is MSVC 19.29.30153.0
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: D:/VisualStudio/vs2019/IDE/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: D:/VisualStudio/vs2019/IDE/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Found Python3: E:\miniconda\envs\foundationpose\python.exe (found version "3.9.20") found components: Interpreter Development.Module
        -- CONFIGURE_COMMAND: ./bootstrap.sh;--prefix=C:/Users/35964/AppData/Local/Temp/cmeel-h_3vu6vg/whl/cmeel.prefix
        -- BUILD_COMMAND: ./b2;hardcode-dll-paths=true;dll-path='$ORIGIN';link=shared;python=3.9
        -- Configuring done (4.8s)
        -- Generating done (0.0s)
        CMake Warning:
          Manually-specified variables were not used by the project:

            BUILD_TESTING
            Boost_NO_WARN_NEW_VERSIONS
            CMAKE_APPLE_SILICON_PROCESSOR
            CMAKE_INSTALL_LIBDIR
            CMEEL_JOBS
            PYTHON_SITELIB


        -- Build files have been written to: C:/Users/35964/AppData/Local/Temp/cmeel-h_3vu6vg/bld
        用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
        版权所有(C) Microsoft Corporation。保留所有权利。

        D:\VisualStudio\vs2019\IDE\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(517,5): warning MSB8029: 中间目录或输出目录无法驻留在临时目录下，因为这可能会导致增量生成出现问题。 [C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\ZERO_CHECK.vcxproj]
          1>Checking Build System
        D:\VisualStudio\vs2019\IDE\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(517,5): warning MSB8029: 中间目录或输出目录无法驻留在临时目录下，因为这可能会导致增量生成出现问题。 [C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\Boost.vcxproj]
          Creating directories for 'Boost'
          Building Custom Rule C:/Users/35964/AppData/Local/Temp/pip-install-obptpif1/cmeel-boost_351f0e832e354ea59de3e16fc574567d/CMakeLists.txt
          Performing download step (download, verify and extract) for 'Boost'
          -- Downloading...
             dst='C:/Users/35964/AppData/Local/Temp/cmeel-h_3vu6vg/bld/Boost-prefix/src/boost_1_83_0.tar.bz2'
             timeout='none'
             inactivity timeout='none'
          -- Using src='https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2'
          -- [download 0% complete]
          -- [download 1% complete]
          -- [download 2% complete]
          -- [download 3% complete]
          -- [download 4% complete]
          -- [download 5% complete]
          -- [download 6% complete]
          -- [download 7% complete]
          -- [download 8% complete]
          -- [download 9% complete]
          -- [download 10% complete]
          -- [download 11% complete]
          -- [download 12% complete]
          -- [download 13% complete]
          -- [download 14% complete]
          -- [download 15% complete]
          -- [download 16% complete]
          -- [download 17% complete]
          -- [download 18% complete]
          -- [download 19% complete]
          -- [download 20% complete]
          -- [download 21% complete]
          -- [download 22% complete]
          -- [download 23% complete]
          -- [download 24% complete]
          -- [download 25% complete]
          -- [download 26% complete]
          -- [download 27% complete]
          -- [download 28% complete]
          -- [download 29% complete]
          -- [download 30% complete]
          -- [download 31% complete]
          -- [download 32% complete]
          -- [download 33% complete]
          -- [download 34% complete]
          -- [download 35% complete]
          -- [download 36% complete]
          -- [download 37% complete]
          -- [download 38% complete]
          -- [download 39% complete]
          -- [download 40% complete]
          -- [download 41% complete]
          -- [download 42% complete]
          -- [download 43% complete]
          -- [download 44% complete]
          -- [download 45% complete]
          -- [download 46% complete]
          -- [download 47% complete]
          -- [download 48% complete]
          -- [download 49% complete]
          -- [download 50% complete]
          -- [download 51% complete]
          -- [download 52% complete]
          -- [download 53% complete]
          -- [download 54% complete]
          -- [download 55% complete]
          -- [download 56% complete]
          -- [download 57% complete]
          -- [download 58% complete]
          -- [download 59% complete]
          -- [download 60% complete]
          -- [download 61% complete]
          -- [download 62% complete]
          -- [download 63% complete]
          -- [download 64% complete]
          -- [download 65% complete]
          -- [download 66% complete]
          -- [download 67% complete]
          -- [download 68% complete]
          -- [download 69% complete]
          -- [download 70% complete]
          -- [download 71% complete]
          -- [download 72% complete]
          -- [download 73% complete]
          -- [download 74% complete]
          -- [download 75% complete]
          -- [download 76% complete]
          -- [download 77% complete]
          -- [download 78% complete]
          -- [download 79% complete]
          -- [download 80% complete]
          -- [download 81% complete]
          -- [download 82% complete]
          -- [download 83% complete]
          -- [download 84% complete]
          -- [download 85% complete]
          -- [download 86% complete]
          -- [download 87% complete]
          -- [download 88% complete]
          -- [download 89% complete]
          -- [download 90% complete]
          -- [download 91% complete]
          -- [download 92% complete]
          -- [download 93% complete]
          -- [download 94% complete]
          -- [download 95% complete]
          -- [download 96% complete]
          -- [download 97% complete]
          -- [download 98% complete]
          -- [download 99% complete]
          -- [download 100% complete]
          -- verifying file...
                 file='C:/Users/35964/AppData/Local/Temp/cmeel-h_3vu6vg/bld/Boost-prefix/src/boost_1_83_0.tar.bz2'
          -- Downloading... done
          -- extracting...
               src='C:/Users/35964/AppData/Local/Temp/cmeel-h_3vu6vg/bld/Boost-prefix/src/boost_1_83_0.tar.bz2'
               dst='C:/Users/35964/AppData/Local/Temp/cmeel-h_3vu6vg/bld/Boost-prefix/src/Boost'
          -- extracting... [tar xfz]
          -- extracting... [analysis]
          -- extracting... [rename]
          -- extracting... [clean up]
          -- extracting... done
          No update step for 'Boost'
          No patch step for 'Boost'
          Performing configure step for 'Boost'
          Traceback (most recent call last):
            File "<string>", line 1, in <module>
          FileNotFoundError: [Errno 2] No such file or directory: 'project-config.jam'
        D:\VisualStudio\vs2019\IDE\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: “C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-mkdir.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-download.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-update.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-patch.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-configure.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-build.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\64eed32b9d01b90e8d7b91833500d12f\Boost-install.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\0c646bd2ade4b3a0bf8ecef7fd49b080\Boost-complete.rule;C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\CMakeFiles\2457c3659b2032343921fc13f6b653ab\Boost.rule;C:\Users\35964\AppData\Local\Temp\pip-install-obptpif1\cmeel-boost_351f0e832e354ea59de3e16fc574567d\CMakeLists.txt”的自定义生成已退出，代码为 1。 [C:\Users\35964\AppData\Local\Temp\cmeel-h_3vu6vg\bld\Boost.vcxproj]
        Traceback (most recent call last):
          File "E:\miniconda\envs\foundationpose\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
            main()
          File "E:\miniconda\envs\foundationpose\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "E:\miniconda\envs\foundationpose\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
            whl_basename = backend.build_wheel(metadata_directory, config_settings)
          File "C:\Users\35964\AppData\Local\Temp\pip-build-env-0e60am7b\overlay\Lib\site-packages\cmeel\build.py", line 26, in build_wheel
            return build_impl(wheel_directory, editable=False)
          File "C:\Users\35964\AppData\Local\Temp\pip-build-env-0e60am7b\overlay\Lib\site-packages\cmeel\impl.py", line 105, in build_impl
            check_call(build_cmd)
          File "E:\miniconda\envs\foundationpose\lib\subprocess.py", line 373, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '--build', 'C:\\Users\\35964\\AppData\\Local\\Temp\\cmeel-h_3vu6vg\\bld', '-j4']' returned non-zero exit status 1.
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by Rapxuan** [comment]
The pin package is only for Linux, so choose Linux system

**Comment by wenbowen123** [comment]
we only tested Linux, although I've seen some other issues saying they had success on Windows.

**Comment by LiYan-pro** [comment]
Yes it can success to use on windows, but its very complicated.

**Comment by wdy0311** [comment]
> Yes it can success to use on windows, but its very complicated.
if possible, plz let me know how to install on win, thx
