### ISSUE TITLE
run CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh have errors

### ISSUE THREAD

**Issue by QandYH** [NVlabs/FoundationPose#273]
(foundationpose) root@790e385a94bd:~/lanyun-tmp/FoundationPose# CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh
build_all_conda.sh: line 2: $'\r': command not found
build_all_conda.sh: line 4: cd: $'/root/lanyun-tmp/FoundationPose\r/mycpp/': No such file or directory
build_all_conda.sh: line 5: $'\r': command not found
CMake Warning:
  Ignoring extra path from command line:

   ".."

CMake Error: The source directory "/root/lanyun-tmp/FoundationPose" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: the '-j' option requires a positive integer argument
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  --eval=STRING               Evaluate STRING as a makefile statement.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from recipes.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no recipe; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo recipes.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  --trace                     Print tracing information.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for x86_64-pc-linux-gnu
Report bugs to <bug-make@gnu.org>
build_all_conda.sh: line 8: $'\r': command not found
build_all_conda.sh: line 10: cd: $'/root/lanyun-tmp/FoundationPose\r/bundlesdf/mycuda': No such file or directory
build_all_conda.sh: line 11: $'\r': command not found
ERROR: . is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).
build_all_conda.sh: line 13: $'\r': command not found
build_all_conda.sh: line 14: cd: $'/root/lanyun-tmp/FoundationPose\r\r': No such file or directory
![QQ20241211](https://github.com/user-attachments/assets/27002fe7-5e68-4823-bcd4-0b826ffbc787)

**Comment by QandYH** [comment]
I use conda env

**Comment by QandYH** [comment]
(foundationpose) root@fc2188eee0fb:~/lanyun-tmp/FoundationPose# CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:10 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/cmake/data/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR system program_options)
Call Stack (most recent call first):
  /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/cmake/data/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/cmake/data/share/cmake-3.31/Modules/FindBoost.cmake:2409 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
Obtaining file:///root/lanyun-tmp/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  DEPRECATION: Legacy editable install of common==0.0.0 from file:///root/lanyun-tmp/FoundationPose/bundlesdf/mycuda (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for common
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [113 lines of output]
        /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        running develop
        /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running egg_info
        creating common.egg-info
        writing common.egg-info/PKG-INFO
        writing dependency_links to common.egg-info/dependency_links.txt
        writing top-level names to common.egg-info/top_level.txt
        writing manifest file 'common.egg-info/SOURCES.txt'
        reading manifest file 'common.egg-info/SOURCES.txt'
        writing manifest file 'common.egg-info/SOURCES.txt'
        running build_ext
        /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.3) has a minor version mismatch with the version that was used to compile PyTorch (11.8). Most likely this shouldn't be a problem.
          warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
        building 'common' extension
        creating /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
        Emitting ninja build file /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
        Compiling objects...
        Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
        [1/2] /usr/local/cuda/bin/nvcc  -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/root/miniconda/envs/foundationpose/include/python3.9 -I/root/miniconda/envs/foundationpose/include/python3.9 -c -c /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/common.cu -o /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
        FAILED: /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
        /usr/local/cuda/bin/nvcc  -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/root/miniconda/envs/foundationpose/include/python3.9 -I/root/miniconda/envs/foundationpose/include/python3.9 -c -c /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/common.cu -o /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
        /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/common.cu:26:10: fatal error: Eigen/Dense: No such file or directory
           26 | #include "Eigen/Dense"
              |          ^~~~~~~~~~~~~
        compilation terminated.
        [2/2] c++ -MMD -MF /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /root/miniconda/envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /root/miniconda/envs/foundationpose/include -I/root/miniconda/envs/foundationpose/include -fPIC -O2 -isystem /root/miniconda/envs/foundationpose/include -fPIC -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/root/miniconda/envs/foundationpose/include/python3.9 -I/root/miniconda/envs/foundationpose/include/python3.9 -c -c /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/bindings.cpp -o /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
            subprocess.run(
          File "/root/miniconda/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
            setup(
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
            return distutils.core.setup(**attrs)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
            return run_commands(dist)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
            dist.run_commands()
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
            self.run_command(cmd)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
            super().run_command(command)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
            cmd_obj.run()
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 35, in run
            self.install_for_development()
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 112, in install_for_development
            self.run_command('build_ext')
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
            self.distribution.run_command(command)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
            super().run_command(command)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
            cmd_obj.run()
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 98, in run
            _build_ext.run(self)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
            self.build_extensions()
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
            build_ext.build_extensions(self)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
            self._build_extensions_serial()
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
            self.build_extension(ext)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
            _build_ext.build_extension(self, ext)
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
            objects = self.compiler.compile(
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
            _write_ninja_file_and_compile_objects(
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
            _run_ninja_build(
          File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
            raise RuntimeError(message) from e
        RuntimeError: Error compiling objects for extension
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [113 lines of output]
    /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cflags'
      warnings.warn(msg)
    /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
      warnings.warn(msg)
    running develop
    /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    creating common.egg-info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    writing manifest file 'common.egg-info/SOURCES.txt'
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    /root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.3) has a minor version mismatch with the version that was used to compile PyTorch (11.8). Most likely this shouldn't be a problem.
      warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
    building 'common' extension
    creating /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
    Emitting ninja build file /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] /usr/local/cuda/bin/nvcc  -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/root/miniconda/envs/foundationpose/include/python3.9 -I/root/miniconda/envs/foundationpose/include/python3.9 -c -c /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/common.cu -o /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
    FAILED: /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
    /usr/local/cuda/bin/nvcc  -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/root/miniconda/envs/foundationpose/include/python3.9 -I/root/miniconda/envs/foundationpose/include/python3.9 -c -c /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/common.cu -o /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
    /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/common.cu:26:10: fatal error: Eigen/Dense: No such file or directory
       26 | #include "Eigen/Dense"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    [2/2] c++ -MMD -MF /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /root/miniconda/envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /root/miniconda/envs/foundationpose/include -I/root/miniconda/envs/foundationpose/include -fPIC -O2 -isystem /root/miniconda/envs/foundationpose/include -fPIC -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/root/miniconda/envs/foundationpose/include/python3.9 -I/root/miniconda/envs/foundationpose/include/python3.9 -c -c /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/bindings.cpp -o /root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
        subprocess.run(
      File "/root/miniconda/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/root/lanyun-tmp/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
        setup(
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
        return run_commands(dist)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
        dist.run_commands()
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
        self.run_command(cmd)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
        super().run_command(command)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 35, in run
        self.install_for_development()
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 112, in install_for_development
        self.run_command('build_ext')
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
        super().run_command(command)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 98, in run
        _build_ext.run(self)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
        self._build_extensions_serial()
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
        self.build_extension(ext)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
        _build_ext.build_extension(self, ext)
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
        objects = self.compiler.compile(
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/root/miniconda/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

now is this error,seem a cmake error.

**Comment by wuwulin** [comment]
I faced the same question,do you have solved it

**Comment by QandYH** [comment]
> 我遇到了同样的问题，你解决了吗

I have solved it just now.I think you should install eigen3.like this https://blog.csdn.net/p942005405/article/details/100653731

**Comment by HelloAlgorithmBob** [comment]
> > 我遇到了同样的问题，你解决了吗
> 
> I have solved it just now.I think you should install eigen3.like this https://blog.csdn.net/p942005405/article/details/100653731

Could give more details about how to solve it? I have re install eigen3 like what you said in the link but there is still error.
