### ISSUE TITLE
Error in building build_all_conda.sh. "#error You need C++17 to compile PyTorch"

### ISSUE THREAD

**Issue by aiihn** [NVlabs/FoundationPose#35]
error info:

```
Obtaining file:///dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  Running setup.py develop for common
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [156 lines of output]
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
        !!
        
                ********************************************************************************
                Usage of dash-separated 'index-url' will not be supported in future
                versions. Please use the underscore name 'index_url' instead.
        
                This deprecation is overdue, please update your project and remove deprecated
                calls to avoid build errors in the future.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          opt = self.warn_dash_deprecation(opt, section)
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        running develop
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running egg_info
        creating common.egg-info
        writing common.egg-info/PKG-INFO
        writing dependency_links to common.egg-info/dependency_links.txt
        writing top-level names to common.egg-info/top_level.txt
        writing manifest file 'common.egg-info/SOURCES.txt'
        reading manifest file 'common.egg-info/SOURCES.txt'
        writing manifest file 'common.egg-info/SOURCES.txt'
        running build_ext
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:425: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
          warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
        building 'common' extension
        creating /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build
        creating /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
        Emitting ninja build file /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
        Compiling objects...
        Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
        [1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o.d -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include/python3.9 -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include/python3.9 -c -c /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/common.cu -o /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
        FAILED: /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
        /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o.d -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include/python3.9 -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include/python3.9 -c -c /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/common.cu -o /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
        In file included from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/util/TypeList.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/util/Metaprogramming.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/core/DispatchKeySet.h:4,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/core/Backend.h:5,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/core/Layout.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/core/impl/PyInterpreter.h:4,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/core/impl/GPUTrace.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/cuda/CUDAFunctions.h:11,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContextLight.h:19,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:3,
                         from /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/common.cu:17:
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
           27 | #error You need C++17 to compile PyTorch
              |  ^~~~~
        In file included from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                         from /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/common.cu:18:
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
            4 | #error C++17 or later compatible compiler is required to use PyTorch.
              |  ^~~~~
        In file included from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                         from /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                         from /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/common.cu:18:
        /dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
            4 | #error C++17 or later compatible compiler is required to use ATen.
              |  ^~~~~
        [2/2] c++ -MMD -MF /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /dev/shm/user1/user2_data/conda_envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /dev/shm/user1/user2_data/conda_envs/foundationpose/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include -fPIC -O2 -isystem /dev/shm/user1/user2_data/conda_envs/foundationpose/include -fPIC -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include/python3.9 -I/dev/shm/user1/user2_data/conda_envs/foundationpose/include/python3.9 -c -c /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/bindings.cpp -o /dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
            subprocess.run(
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/dev/shm/user1/sds_scene_proj/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
            setup(
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
            return distutils.core.setup(**attrs)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
            super().run_command(command)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 109, in install_for_development
            self.run_command('build_ext')
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
            super().run_command(command)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 88, in run
            _build_ext.run(self)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
            self.build_extensions()
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 871, in build_extensions
            build_ext.build_extensions(self)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
            self._build_extensions_serial()
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
            self.build_extension(ext)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
            _build_ext.build_extension(self, ext)
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
            objects = self.compiler.compile(
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 684, in unix_wrap_ninja_compile
            _write_ninja_file_and_compile_objects(
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
            _run_ninja_build(
          File "/dev/shm/user1/user2_data/conda_envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
            raise RuntimeError(message) from e
        RuntimeError: Error compiling objects for extension
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by aiihn** [comment]
The issue was resolved by changing 'c++14' to 'c++17' in the file bundlesdf/mycuda/setup.py as below:
```
nvcc_flags = ['-Xcompiler', '-O3', '-std=c++17', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__']
c_flags = ['-O3', '-std=c++17']
```
