### ISSUE TITLE
ValueError: primitive vertices are immutable: not setting! 

### ISSUE THREAD

**Issue by wsq1010** [NVlabs/FoundationPose#39]
Traceback (most recent call last):
  File "run_ycb_video.py", line 149, in <module>
    run_pose_estimation()
  File "run_ycb_video.py", line 94, in run_pose_estimation
    est = FoundationPose(model_pts=mesh_tmp.vertices.copy(), model_normals=mesh_tmp.vertex_normals.copy(), symmetry_tfs=None, mesh=mesh_tmp, scorer=None, refiner=None, glctx=glctx, debug_dir=debug_dir, debug=debug)
  File "/home/bowen/FoundationPose/estimater.py", line 26, in __init__
    self.reset_object(model_pts, model_normals, symmetry_tfs=symmetry_tfs, mesh=mesh)
  File "/home/bowen/FoundationPose/estimater.py", line 58, in reset_object
    mesh.vertices = mesh.vertices - self.model_center.reshape(1,3)
  File "/opt/conda/envs/my/lib/python3.8/site-packages/trimesh/primitives.py", line 76, in vertices
    raise ValueError("primitive vertices are immutable: not setting!")

**Comment by wsq1010** [comment]
Hello I solved this problem in run_ycb_video.py in line 93 mesh_tmp = trimesh.primitives.Box(extents=np.ones((3)),transform=np.eye(4)) is missing after to_mesh()
