### ISSUE TITLE
Running model-based linemod fails because theres no scene_camera.json

### ISSUE THREAD

**Issue by sabinecelina** [NVlabs/FoundationPose#45]
Hello, 

I downloaded the linemod dataset and ran the command with the correct path to my dataset: 
```
 python run_linemod.py --linemod_dir model_free/linemod/ --use_reconstructed_mesh 0
```
I get the error:
```
File "/mnt/workspace/foundation-pose/datareader.py", line 166, in __init__
    with open(f'{self.base_dir}/scene_camera.json','r') as ff:
FileNotFoundError: [Errno 2] No such file or directory: 'model_free/linemod/lm_test_all/test/000002/scene_camera.json'.
```

But I don't see this file in the linemod dataset. 

Trying to run the other dataset "ycbv" I also get an error: 
```
Traceback (most recent call last):
  File "run_ycb_video.py", line 149, in <module>
    run_pose_estimation()
  File "run_ycb_video.py", line 91, in run_pose_estimation
    reader_tmp = YcbVideoReader(video_dirs[0])
IndexError: list index out of range
```

And I don't know how to handle it.

**Comment by Launch-on-Titania** [comment]
For me, following the link:
```
https://bop.felk.cvut.cz/media/data/bop_datasets/lm_test_all.zip
```
I did not meet this problem

**Comment by sabinecelina** [comment]
Solved it by downloading the lm_test_all.zip dataset and the lm_models.zip dataset.
