### ISSUE TITLE
about"build_all_conda.sh"error：UserWarning: Unknown distribution option: 'extra_cflags' 

### ISSUE THREAD

**Issue by yuhanggeng123** [NVlabs/FoundationPose#66]
**Thank the person who can solve the problem**
  Running setup.py develop for common
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [79 lines of output]
        /home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:266: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        running develop
        /home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************

        !!
          easy_install.initialize_options(self)
        /home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!

                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.

                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************

        !!
          self.initialize_options()
        running egg_info
        creating common.egg-info
        writing common.egg-info/PKG-INFO
        writing dependency_links to common.egg-info/dependency_links.txt
        writing top-level names to common.egg-info/top_level.txt
        writing manifest file 'common.egg-info/SOURCES.txt'
        reading manifest file 'common.egg-info/SOURCES.txt'
        writing manifest file 'common.egg-info/SOURCES.txt'
        running build_ext
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/g/FoundationPose/bundlesdf/mycuda/setup.py", line 21, in <module>
            setup(
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
            return distutils.core.setup(**attrs)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
            return run_commands(dist)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
            dist.run_commands()
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
            super().run_command(command)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 111, in install_for_development
            self.run_command('build_ext')
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
            self.distribution.run_command(command)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
            super().run_command(command)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 91, in run
            _build_ext.run(self)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
            self.build_extensions()
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
            _check_cuda_version(compiler_name, compiler_version)
          File "/home/g/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
            raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
        RuntimeError:
        The detected CUDA version (12.2) mismatches the version that was used to compile
        PyTorch (11.8). Please make sure to use the same CUDA versions.

        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by wenbowen123** [comment]
Hi, right now you are having some mismatched packages. Did you try docker?

**Comment by yuhanggeng123** [comment]
> Hi, right now you are having some mismatched packages. Did you try docker?

Thanks for your reply, I successfully implemented by changing the cuda version

**Comment by IoannisDadiotis** [comment]
> > Hi, right now you are having some mismatched packages. Did you try docker?
> 
> Thanks for your reply, I successfully implemented by changing the cuda version

Hey @yuhanggeng123 , I have the same error (cuda mismatch). Do you remember the exact steps to solve this?

**Comment by csjiyw** [comment]
> version that was used to compile
>     PyTorch (11.8). Please m

conda install cuda -c nvidia/label/cuda-11.8.0
