### ISSUE TITLE
Based on conda:RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by 1230678** [NVlabs/FoundationPose#68]
I'm looking for help with an issue encountered while trying to reproduce using the conda method.

error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [90 lines of output]
    /home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_cflags'
      warnings.warn(msg)
    /home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
      warnings.warn(msg)
    running develop
    /home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    creating common.egg-info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    writing manifest file 'common.egg-info/SOURCES.txt'
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    /home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
      warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
    building 'common' extension
    creating /home/eric/FoundationPose-main/bundlesdf/mycuda/build
    creating /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39
    Emitting ninja build file /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/2] /usr/local/cuda/bin/bin/nvcc  -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/bin/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/eric/anaconda3/envs/foundationpose/include/python3.9 -I/home/eric/anaconda3/envs/foundationpose/include/python3.9 -c -c /home/eric/FoundationPose-main/bundlesdf/mycuda/common.cu -o /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
    FAILED: /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o
    /usr/local/cuda/bin/bin/nvcc  -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/bin/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/eric/anaconda3/envs/foundationpose/include/python3.9 -I/home/eric/anaconda3/envs/foundationpose/include/python3.9 -c -c /home/eric/FoundationPose-main/bundlesdf/mycuda/common.cu -o /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/common.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -Xcompiler -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89
    cc1plus: fatal error: cuda_runtime.h: 没有那个文件或目录
    compilation terminated.
    [2/2] c++ -MMD -MF /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o.d -pthread -B /home/eric/anaconda3/envs/foundationpose/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/eric/anaconda3/envs/foundationpose/include -I/home/eric/anaconda3/envs/foundationpose/include -fPIC -O2 -isystem /home/eric/anaconda3/envs/foundationpose/include -fPIC -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/TH -I/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/bin/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/home/eric/anaconda3/envs/foundationpose/include/python3.9 -I/home/eric/anaconda3/envs/foundationpose/include/python3.9 -c -c /home/eric/FoundationPose-main/bundlesdf/mycuda/bindings.cpp -o /home/eric/FoundationPose-main/bundlesdf/mycuda/build/temp.linux-x86_64-cpython-39/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=common -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
        subprocess.run(
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/eric/FoundationPose-main/bundlesdf/mycuda/setup.py", line 21, in <module>
        setup(
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 1224, in run_command
        super().run_command(command)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/dist.py", line 1224, in run_command
        super().run_command(command)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/home/eric/anaconda3/envs/foundationpose/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

**Comment by wenbowen123** [comment]
it seems like you didn't install cuda. Did you try docker instead?

**Comment by 1230678** [comment]
Thank you very much for your response. CUDA and Torch have been configured successfully, but I encountered this error. I am currently trying to use Docker, which I haven't used before, to solve it.

**Comment by LittlePotatoChip** [comment]
same quetions，I have tried docker version，but mirror sites is not usable recently. how can I sovle it？
