### ISSUE TITLE
Something wrong when I run python bundlesdf/run_nerf.py

### ISSUE THREAD

**Issue by LiYan0306** [NVlabs/FoundationPose#76]
1. **Question:** 

      **When I run `python run_nerf.py ` have meet a error.**
      When I run `python run_demo.py` is right.
      Could you please help me to fix it ,thank you very much.

2. **Enviroment:** 

      Docker ：nvidia/cuda:11.8.0-cudnn8-devel-ubuntu18.04
      4090 win11

3. **Whole Traceback:** 

Traceback (most recent call last):
  File "/foundationPose/FoundationPose-main/bundlesdf/run_nerf.py", line 117, in <module>
    run_ycbv()
  File "/foundationPose/FoundationPose-main/bundlesdf/run_nerf.py", line 89, in run_ycbv
    mesh = run_one_ob(base_dir=base_dir, cfg=cfg)
  File "/foundationPose/FoundationPose-main/bundlesdf/run_nerf.py", line 77, in run_one_ob
    mesh = run_neural_object_field(cfg, K, rgbs, depths, masks, cam_in_obs, save_dir=save_dir, debug=0)
  File "/foundationPose/FoundationPose-main/bundlesdf/run_nerf.py", line 47, in run_neural_object_field
    mesh = nerf.mesh_texture_from_train_images(mesh, rgbs_raw=rgbs, tex_res=1028)
  File "/foundationPose/FoundationPose-main/bundlesdf/nerf_runner.py", line 1154, in mesh_texture_from_train_images
    _, render_depth = renderer.render(mesh=mesh, ob_in_cvcam=np.linalg.inv(cvcam_in_ob))
  File "/foundationPose/FoundationPose-main/bundlesdf/../offscreen_renderer.py", line 75, in render
    color, depth = self.r.render(self.scene)  # depth: float
  File "/root/miniconda3/envs/foundationpose/lib/python3.9/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/root/miniconda3/envs/foundationpose/lib/python3.9/site-packages/pyrender/renderer.py", line 144, in render
    retval = self._forward_pass(scene, flags, seg_node_map=seg_node_map)
  File "/root/miniconda3/envs/foundationpose/lib/python3.9/site-packages/pyrender/renderer.py", line 326, in _forward_pass
    self._configure_forward_pass_viewport(flags)
  File "/root/miniconda3/envs/foundationpose/lib/python3.9/site-packages/pyrender/renderer.py", line 1012, in _configure_forward_pass_viewport
    self._configure_main_framebuffer()
  File "/root/miniconda3/envs/foundationpose/lib/python3.9/site-packages/pyrender/renderer.py", line 1092, in _configure_main_framebuffer
    glRenderbufferStorageMultisample(
  File "/root/miniconda3/envs/foundationpose/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glRenderbufferStorageMultisample,
        cArguments = (GL_RENDERBUFFER, 4, GL_RGBA, 640, 480)
)
free(): invalid pointer
Aborted

**Comment by LiYan0306** [comment]
I fixed this problem by [on Jan 10, 2021](https://github.com/mmatl/pyrender/issues/77#issuecomment-757402914)
