### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cluster_poses'

### ISSUE THREAD

**Issue by NTheodoris** [NVlabs/FoundationPose#91]
When i try to run demo.py in conda envionment, i get this error   Warp 1.0.2 initialized:
   CUDA Toolkit 11.5, Driver 12.4
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 3060" (12 GiB, sm_86, mempool enabled)
   Kernel cache:
     /home/lms/.cache/warp/1.0.2
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
- 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

[__init__()] self.h5_file:None
[__init__()] Using pretrained model from /home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
- 160
- 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
- 0.019999999552965164
- 0.019999999552965164
- 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

[__init__()] self.h5_file:
[__init__()] Using pretrained model from /home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[reset_object()] self.diameter:0.19646325799497472, vox_size:0.009823162899748735
[reset_object()] self.pts:torch.Size([607, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
Traceback (most recent call last):
  File "/home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/run_demo.py", line 41, in <module>
    est = FoundationPose(model_pts=mesh.vertices, model_normals=mesh.vertex_normals, mesh=mesh, scorer=scorer, refiner=refiner, debug_dir=debug_dir, debug=debug, glctx=glctx)
  File "/home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/estimater.py", line 27, in __init__
    self.make_rotation_grid(min_n_views=40, inplane_step=60)
  File "/home/lms/Github/deep_learning_vision_methods/src/foundation_pose6d/estimater.py", line 120, in make_rotation_grid
    rot_grid = mycpp.cluster_poses(30, 99999, rot_grid, self.symmetry_tfs.data.cpu().numpy())
AttributeError: 'NoneType' object has no attribute 'cluster_poses'

**Comment by juwangvsu** [comment]
I have the same problem (4070), would you mind sharing your solution if you have solved the issue?

**Comment by juwangvsu** [comment]
never mind, find a solution at #89. clean rebuild mycpp after the 4090 hack

**Comment by alakhag** [comment]
I'm not sure what am I missing, but it seems odd, if in estimator.py, mycpp is not imported or initialized, how can it not be None?

> (foundationpose) alakhaggarwal@alakhaggarwal-Precision-WorkStation-T7500:/home/alakhaggarwal/illumination-proj/FoundationPose/docker$ bash run_container.sh 
foundationpose
access control disabled, clients can connect from any host
(my) root@alakhaggarwal-Precision-WorkStation-T7500:/home/alakhaggarwal/illumination-proj/FoundationPose# bash build_all.sh 
-- Found pybind11: /home/alakhaggarwal/mambaforge/envs/foundationpose/lib/python3.9/site-packages/pybind11/include (found version "2.12.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alakhaggarwal/illumination-proj/FoundationPose/mycpp/build
[100%] Built target mycpp
Obtaining file:///kaolin
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ipycanvas in /opt/conda/envs/my/lib/python3.8/site-packages/ipycanvas-0.13.1-py3.8.egg (from kaolin==0.15.0) (0.13.1)
Requirement already satisfied: ipyevents in /opt/conda/envs/my/lib/python3.8/site-packages/ipyevents-2.0.2-py3.8.egg (from kaolin==0.15.0) (2.0.2)
Requirement already satisfied: jupyter_client<8 in /opt/conda/envs/my/lib/python3.8/site-packages/jupyter_client-7.4.9-py3.8.egg (from kaolin==0.15.0) (7.4.9)
Requirement already satisfied: pyzmq<25 in /opt/conda/envs/my/lib/python3.8/site-packages/pyzmq-24.0.1-py3.8-linux-x86_64.egg (from kaolin==0.15.0) (24.0.1)
Requirement already satisfied: flask in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (3.0.2)
Requirement already satisfied: tornado in /opt/conda/envs/my/lib/python3.8/site-packages/tornado-6.4-py3.8-linux-x86_64.egg (from kaolin==0.15.0) (6.4)
Requirement already satisfied: comm>=0.1.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (0.2.2)
Requirement already satisfied: numpy in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (1.24.3)
Requirement already satisfied: pybind11 in /opt/conda/envs/my/lib/python3.8/site-packages/pybind11-2.11.1-py3.8.egg (from kaolin==0.15.0) (2.11.1)
Requirement already satisfied: Pillow>=8.0.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (10.2.0)
Requirement already satisfied: tqdm>=4.51.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (4.66.2)
Requirement already satisfied: scipy in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (1.10.1)
Requirement already satisfied: pygltflib in /opt/conda/envs/my/lib/python3.8/site-packages/pygltflib-1.16.2-py3.8.egg (from kaolin==0.15.0) (1.16.2)
Requirement already satisfied: usd-core<=23.5 in /opt/conda/envs/my/lib/python3.8/site-packages/usd_core-23.5-py3.8-linux-x86_64.egg (from kaolin==0.15.0) (23.5)
Requirement already satisfied: ipython<8.13 in /opt/conda/envs/my/lib/python3.8/site-packages (from kaolin==0.15.0) (8.12.3)
Requirement already satisfied: traitlets>=4 in /opt/conda/envs/my/lib/python3.8/site-packages (from comm>=0.1.3->kaolin==0.15.0) (5.14.2)
Requirement already satisfied: backcall in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.2.0)
Requirement already satisfied: decorator in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.19.1)
Requirement already satisfied: matplotlib-inline in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.1.6)
Requirement already satisfied: pickleshare in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (2.17.2)
Requirement already satisfied: stack-data in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (0.6.3)
Requirement already satisfied: typing-extensions in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (4.10.0)
Requirement already satisfied: pexpect>4.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipython<8.13->kaolin==0.15.0) (4.9.0)
Requirement already satisfied: entrypoints in /opt/conda/envs/my/lib/python3.8/site-packages/entrypoints-0.4-py3.8.egg (from jupyter_client<8->kaolin==0.15.0) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter_client<8->kaolin==0.15.0) (5.7.2)
Requirement already satisfied: nest-asyncio>=1.5.4 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter_client<8->kaolin==0.15.0) (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter_client<8->kaolin==0.15.0) (2.9.0.post0)
Requirement already satisfied: Werkzeug>=3.0.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (3.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (1.7.0)
Requirement already satisfied: importlib-metadata>=3.6.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from flask->kaolin==0.15.0) (7.0.2)
Requirement already satisfied: ipywidgets<9,>=7.6.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipycanvas->kaolin==0.15.0) (8.1.2)
Requirement already satisfied: dataclasses-json>=0.0.25 in /opt/conda/envs/my/lib/python3.8/site-packages/dataclasses_json-0.6.4-py3.8.egg (from pygltflib->kaolin==0.15.0) (0.6.4)
Requirement already satisfied: deprecated in /opt/conda/envs/my/lib/python3.8/site-packages/Deprecated-1.2.14-py3.8.egg (from pygltflib->kaolin==0.15.0) (1.2.14)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /opt/conda/envs/my/lib/python3.8/site-packages/marshmallow-3.21.1-py3.8.egg (from dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (3.21.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /opt/conda/envs/my/lib/python3.8/site-packages/typing_inspect-0.9.0-py3.8.egg (from dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (0.9.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from importlib-metadata>=3.6.0->flask->kaolin==0.15.0) (3.17.0)
Requirement already satisfied: widgetsnbextension~=4.0.10 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipywidgets<9,>=7.6.0->ipycanvas->kaolin==0.15.0) (4.0.10)
Requirement already satisfied: jupyterlab-widgets~=3.0.10 in /opt/conda/envs/my/lib/python3.8/site-packages (from ipywidgets<9,>=7.6.0->ipycanvas->kaolin==0.15.0) (3.0.10)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/conda/envs/my/lib/python3.8/site-packages (from jedi>=0.16->ipython<8.13->kaolin==0.15.0) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from Jinja2>=3.1.2->flask->kaolin==0.15.0) (2.1.3)
Requirement already satisfied: platformdirs>=2.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from jupyter-core>=4.9.2->jupyter_client<8->kaolin==0.15.0) (4.2.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from pexpect>4.3->ipython<8.13->kaolin==0.15.0) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/envs/my/lib/python3.8/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython<8.13->kaolin==0.15.0) (0.2.13)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/my/lib/python3.8/site-packages (from python-dateutil>=2.8.2->jupyter_client<8->kaolin==0.15.0) (1.16.0)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/conda/envs/my/lib/python3.8/site-packages/wrapt-1.16.0-py3.8.egg (from deprecated->pygltflib->kaolin==0.15.0) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from stack-data->ipython<8.13->kaolin==0.15.0) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from stack-data->ipython<8.13->kaolin==0.15.0) (2.4.1)
Requirement already satisfied: pure-eval in /opt/conda/envs/my/lib/python3.8/site-packages (from stack-data->ipython<8.13->kaolin==0.15.0) (0.2.2)
Requirement already satisfied: packaging>=17.0 in /opt/conda/envs/my/lib/python3.8/site-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (24.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /opt/conda/envs/my/lib/python3.8/site-packages/mypy_extensions-1.0.0-py3.8.egg (from typing-inspect<1,>=0.4.0->dataclasses-json>=0.0.25->pygltflib->kaolin==0.15.0) (1.0.0)
Installing collected packages: kaolin
  Running setup.py develop for kaolin
Successfully installed kaolin-0.15.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Obtaining file:///home/alakhaggarwal/illumination-proj/FoundationPose/bundlesdf/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  Running setup.py develop for common
Successfully installed common-0.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(my) root@alakhaggarwal-Precision-WorkStation-T7500:/home/alakhaggarwal/illumination-proj/FoundationPose# python run_demo.py 
Warp 1.0.0 initialized:
   CUDA Toolkit 11.5, Driver 12.0
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 2080 Ti" (11 GiB, sm_75, mempool enabled)
     "cuda:1"   : "NVIDIA GeForce RTX 2080 Ti" (11 GiB, sm_75, mempool enabled)
   CUDA peer access:
     Not supported
   Kernel cache:
     /root/.cache/warp/1.0.0
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
> - 160
> - 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
> - 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

> [__init__()] self.h5_file:None
[__init__()] Using pretrained model from /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
> - 160
> - 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
> - 0.019999999552965164
> - 0.019999999552965164
> - 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

> [__init__()] self.h5_file:
[__init__()] Using pretrained model from /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[reset_object()] self.diameter:0.1983765857605176, vox_size:0.00991882928802588
[reset_object()] self.pts:torch.Size([568, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
Traceback (most recent call last):
  File "run_demo.py", line 41, in <module>
    est = FoundationPose(model_pts=mesh.vertices, model_normals=mesh.vertex_normals, mesh=mesh, scorer=scorer, refiner=refiner, debug_dir=debug_dir, debug=debug, glctx=glctx)
  File "/home/alakhaggarwal/illumination-proj/FoundationPose/estimater.py", line 27, in __init__
    self.make_rotation_grid(min_n_views=40, inplane_step=60)
  File "/home/alakhaggarwal/illumination-proj/FoundationPose/estimater.py", line 120, in make_rotation_grid
    rot_grid = mycpp.cluster_poses(30, 99999, rot_grid, self.symmetry_tfs.data.cpu().numpy())
AttributeError: 'NoneType' object has no attribute 'cluster_poses'
(my) root@alakhaggarwal-Precision-WorkStation-T7500:/home/alakhaggarwal/illumination-proj/FoundationPose# python run_demo.py 
Warp 1.0.0 initialized:
   CUDA Toolkit 11.5, Driver 12.0
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 2080 Ti" (11 GiB, sm_75, mempool enabled)
     "cuda:1"   : "NVIDIA GeForce RTX 2080 Ti" (11 GiB, sm_75, mempool enabled)
   CUDA peer access:
     Not supported
   Kernel cache:
     /root/.cache/warp/1.0.0
> [__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: 'Infinity'
debug: null
n_view: 1
run_id: 3wy8qqex
use_BN: true
exp_name: 2024-01-11-20-02-45
n_epochs: 62
save_dir: /home/bowenw/debug/2024-01-11-20-02-45/
use_mask: false
loss_type: pairwise_valid
optimizer: adam
batch_size: 64
crop_ratio: 1.1
enable_amp: true
use_normal: false
max_num_key: null
warmup_step: -1
input_resize:
> - 160
> - 160
max_step_val: 1000
vis_interval: 1000
weight_decay: 0
normalize_xyz: true
resume_run_id: null
clip_grad_norm: 'Infinity'
lr_epoch_decay: 500
render_backend: nvdiffrast
train_num_pair: 5
lr_decay_epochs:
> - 50
n_epochs_warmup: 1
make_pair_online: false
gradient_max_norm: 'Infinity'
max_step_per_epoch: 10000
n_rendering_workers: 1
save_epoch_interval: 100
n_dataloader_workers: 100
split_objects_across_gpus: true
ckpt_dir: /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth

> [__init__()] self.h5_file:None
[__init__()] Using pretrained model from /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2024-01-11-20-02-45/model_best.pth
[__init__()] init done
[__init__()] welcome
[__init__()] self.cfg: 
 lr: 0.0001
c_in: 6
zfar: .inf
debug: null
w_rot: 0.1
n_view: 1
run_id: null
use_BN: true
rot_rep: axis_angle
ckpt_dir: /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
exp_name: 2023-10-28-18-33-37
save_dir: /tmp/2023-10-28-18-33-37/
loss_type: l2
optimizer: adam
trans_rep: tracknet
batch_size: 64
crop_ratio: 1.2
use_normal: false
BN_momentum: 0.1
max_num_key: null
warmup_step: -1
input_resize:
> - 160
> - 160
max_step_val: 1000
normal_uint8: false
vis_interval: 1000
weight_decay: 0
n_max_objects: null
normalize_xyz: true
clip_grad_norm: 'Infinity'
rot_normalizer: 0.3490658503988659
trans_normalizer:
> - 0.019999999552965164
> - 0.019999999552965164
> - 0.05000000074505806
max_step_per_epoch: 25000
val_epoch_interval: 10
n_dataloader_workers: 60
enable_amp: true
use_mask: false

> [__init__()] self.h5_file:
[__init__()] Using pretrained model from /home/alakhaggarwal/illumination-proj/FoundationPose/learning/training/../../weights/2023-10-28-18-33-37/model_best.pth
[__init__()] init done
[reset_object()] self.diameter:0.1983765857605176, vox_size:0.00991882928802588
[reset_object()] self.pts:torch.Size([568, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
Traceback (most recent call last):
  File "run_demo.py", line 41, in <module>
    est = FoundationPose(model_pts=mesh.vertices, model_normals=mesh.vertex_normals, mesh=mesh, scorer=scorer, refiner=refiner, debug_dir=debug_dir, debug=debug, glctx=glctx)
  File "/home/alakhaggarwal/illumination-proj/FoundationPose/estimater.py", line 27, in __init__
    self.make_rotation_grid(min_n_views=40, inplane_step=60)
  File "/home/alakhaggarwal/illumination-proj/FoundationPose/estimater.py", line 120, in make_rotation_grid
    rot_grid = mycpp.cluster_poses(30, 99999, rot_grid, self.symmetry_tfs.data.cpu().numpy())
AttributeError: 'NoneType' object has no attribute 'cluster_poses'

**Comment by MY-CODE-1981** [comment]
CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh
After this procedure, a .so file will be created under mycpp/build. If its name is not mycpp.so, an error will occur when executing mycpp.cluster_poses in estimator.py.

The solution is simple: just rename the .so file to mycpp.so. In my case, the name was as follows, and changing it to mycpp.so resolved the issue:
mycpp.cpython-39-x86_64-linux-gnu.so

**Comment by Cheney-36** [comment]
我的40系列显卡运行下面 指令可以不用修改so名字`CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh`

**Comment by Cheney-36** [comment]
My 40 series graphics card can run the following command without modifying the so file name`CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib/python3.9/site-packages/pybind11/share/cmake/pybind11 bash build_all_conda.sh`
